[listen]
host = "0.0.0.0" # default
port = 25565 # default

[[rule]]
match = "shiina.family"
host = "118.157.138.154"
port = 25565 # default

[[rule]]
match = "testoo"
host = "118.157.138.154"
port = 25565 # default

[[rule]]
match = "mc.hypixel.net"
host = "209.222.114.76"
port = 25565 # default
