listen_addr = "0.0.0.0:25565"

[[rule]]
match = "shiina.family"
addr = "127.0.0.1:25566"

[[rule]]
match = "mc.chihuyu.love"
addr = "127.0.0.1:25567"

[[rule]]
match = "testoo"
addr = "118.157.138.154:25565"

[[rule]]
match = "mc.hypixel.net"
addr = "209.222.114.76:25565"